---
application:
  name: "dictionary-media-service"
  project: "Immersion Dictionary"
  organization: "QoveryCommunity"
routers:
- name: "main-dictionary-media-service"
  routes:
  - application_name: "dictionary-media-service"
    paths:
    - "/*"
